apiVersion: v1
kind: Service
metadata:
  name: eventstore-injector
  namespace: ${NAMESPACE}
  labels:
    app: eventstore-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: eventstore-injector