kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventstore-operator
  labels:
    app: eventstore-oprator
subjects:
- kind: ServiceAccount
  name: eventstore-operator
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventstore-operator