apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstore-operator
  labels:
    app: eventstore-operator
rules:
- apiGroups:
  - eventstore.io
  resources:
  - "*"
  verbs:
  - "*"