/*
Copyright AndreasM009.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	eventstorev1alpha1 "github.com/AndreasM009/eventstore/pkg/apis/eventstore/v1alpha1"
	versioned "github.com/AndreasM009/eventstore/pkg/client/clientset/versioned"
	internalinterfaces "github.com/AndreasM009/eventstore/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/AndreasM009/eventstore/pkg/client/listers/eventstore/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EventstoreInformer provides access to a shared informer and lister for
// Eventstores.
type EventstoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EventstoreLister
}

type eventstoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEventstoreInformer constructs a new informer for Eventstore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEventstoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEventstoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEventstoreInformer constructs a new informer for Eventstore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEventstoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventstoreV1alpha1().Eventstores(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EventstoreV1alpha1().Eventstores(namespace).Watch(context.TODO(), options)
			},
		},
		&eventstorev1alpha1.Eventstore{},
		resyncPeriod,
		indexers,
	)
}

func (f *eventstoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEventstoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eventstoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&eventstorev1alpha1.Eventstore{}, f.defaultInformer)
}

func (f *eventstoreInformer) Lister() v1alpha1.EventstoreLister {
	return v1alpha1.NewEventstoreLister(f.Informer().GetIndexer())
}
